{% set name = "samsam" %}
{% set version = "1.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/samsam-{{ version }}.tar.gz
  sha256: eacda5532ccb8360070aba8f9518f671278cccacfb6bb5b452391d22d6709306

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.16
    - python >={{ python_min }}
    - scipy >=1.2

test:
  imports:
    - samsam
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.unige.ch/delisle/samsam
  summary: Scaled Adaptive Metropolis SAMpler.
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbdelisle
