{% set name = "samsam" %}
{% set version = "1.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/samsam-{{ version }}.tar.gz
  sha256: 3fca17099ed99ee33d689e88041e9750b9271c82c38b74f13bf410ffbc88da9f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.16
    - python >=3.6
    - scipy >=1.2

test:
  imports:
    - samsam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.unige.ch/jean-baptiste.delisle/samsam
  summary: Scaled Adaptive Metropolis.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - jbdelisle
