{% set name = "samsam" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/samsam-{{ version }}.tar.gz
  sha256: c8fa7922d2d0c187b4fbb17aa80cd2371a2015715a406e819a85d36ce39051f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.16
    - python >=3.6
    - scipy >=1.2

test:
  imports:
    - samsam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.unige.ch/jean-baptiste.delisle/samsam
  summary: Scaled Adaptive Metropolis.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - jbdelisle
