{% set name = "samsam" %}
{% set version = "1.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/samsam-{{ version }}.tar.gz
  sha256: c9d83f80cc7ba1c75843a7cd46a0fb14f7f80bb74634f03f065094f25f75b83d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy >=1.16
    - python >=3.8
    - scipy >=1.2

test:
  imports:
    - samsam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.unige.ch/delisle/samsam
  summary: Scaled Adaptive Metropolis SAMpler.
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbdelisle
